-- Creación de la base de datos
CREATE DATABASE COMERCIO;

USE COMERCIO;

-- Creación de tabla de productos
CREATE TABLE PRODUCTOS (
    PRO_ID NUMBER NOT NULL,
    PRO_NOMBRE VARCHAR(50) NOT NULL,
    PRO_CAT_ID NUMBER,
    CONSTRAINT pk_pro_id PRIMARY KEY (PRO_ID)
);

-- Creación de tabla de stocks
CREATE TABLE STOCKS (
    STO_ID NUMBER NOT NULL,
    STO_CANT NUMBER NOT NULL,
    STO_PRO_ID NUMBER NOT NULL,
    STO_SUC_ID NUMBER NOT NULL,
    CONSTRAINT pk_sto_id PRIMARY KEY (STO_ID),
    CONSTRAINT fk_sto_pro_id FOREIGN KEY (STO_PRO_ID) REFERENCES PRODUCTOS (PRO_ID),
    CONSTRAINT fk_sto_suc_id FOREIGN KEY (STO_SUC_ID) REFERENCES SUCURSALES (SUC_ID)
);

-- Creación de tabla de sucursales
CREATE TABLE SUCURSALES (
    SUC_ID NUMBER NOT NULL,
    SUC_NOMBRE VARCHAR(50) NOT NULL,
    SUC_DIRECCION VARCHAR(100),
    CONSTRAINT pk_suc_id PRIMARY KEY (SUC_ID)
);

-- Creación de tabla de categorías
CREATE TABLE CATEGORIAS (
    CAT_ID NUMBER NOT NULL,
    CAT_NOMBRE VARCHAR(50) NOT NULL,
    CONSTRAINT pk_cat_id PRIMARY KEY (CAT_ID)
);

-- Inserción de categorías
INSERT INTO CATEGORIAS (CAT_ID, CAT_NOMBRE) VALUES (1, 'Electrónica');
INSERT INTO CATEGORIAS (CAT_ID, CAT_NOMBRE) VALUES (2, 'Ropa');
INSERT INTO CATEGORIAS (CAT_ID, CAT_NOMBRE) VALUES (3, 'Alimentos');

-- Inserción de sucursales
INSERT INTO SUCURSALES (SUC_ID, SUC_NOMBRE, SUC_DIRECCION) VALUES (1, 'Sucursal Centro', 'Calle Principal 123');
INSERT INTO SUCURSALES (SUC_ID, SUC_NOMBRE, SUC_DIRECCION) VALUES (2, 'Sucursal Norte', 'Avenida Norte 456');

-- Inserción de productos
INSERT INTO PRODUCTOS (PRO_ID, PRO_NOMBRE, PRO_CAT_ID) VALUES (1, 'Televisor', 1);
INSERT INTO PRODUCTOS (PRO_ID, PRO_NOMBRE, PRO_CAT_ID) VALUES (2, 'Camiseta', 2);
INSERT INTO PRODUCTOS (PRO_ID, PRO_NOMBRE, PRO_CAT_ID) VALUES (3, 'Pan', 3);

-- Inserción de stocks
INSERT INTO STOCKS (STO_ID, STO_CANT, STO_PRO_ID, STO_SUC_ID) VALUES (1, 50, 1, 1);
INSERT INTO STOCKS (STO_ID, STO_CANT, STO_PRO_ID, STO_SUC_ID) VALUES (2, 30, 2, 1);
INSERT INTO STOCKS (STO_ID, STO_CANT, STO_PRO_ID, STO_SUC_ID) VALUES (3, 100, 3, 2);